### PR TITLE
fix(Validator): added iterator increment in order to prevent nested f…

### PR DESCRIPTION
**Pull request by cstefanache**
…or value override

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Looks great! (I assume it passes the failing test?)

**Comment by cstefanache** [comment]
Yes - the test is ok

**Comment by dmitrizagidulin** [comment]
👍

**Comment by christiansmith** [comment]
Note for posterity, this is a stopgap until we introduce the new compiler model here, which also fixes this issue. 

@dmitrizagidulin nice catch!
@cstefanache thanks for the fix!

**Pull request merged**
